### ISSUE TITLE
Compatible versions of phpBB

### ISSUE THREAD

**Issue by tomaskir** [danirod/phpbb-tagmanager#1]
Hi,

Could you please specify somewhere in the README with which phpBB versions this is compatible with?

Particularly, is it compatible with the 3.2.x branch of phpBB?

Thanks!

**Comment by danirod** [comment]
It is. Currently it is working on a live forum running phpBB 3.2.1. It works on phpBB 3.2.0 as well.

It's a good idea, I'll update the README file.
